version: "3.9" services: web: build: . command: 
    python3 manage.py runserver 0.0.0.0:8000 
    ports:
      - "8000:8000" env_file: - .env 
    depends_on:
      - db db: image: mysql:8.0 restart: always 
    environment:
      MYSQLDB: ${MYSQLDB} MYSQLUSER: 
      ${MYSQLUSER} MYSQL_PASSWORD: 
      ${MYSQL_PASSWORD} MYSQL_ROOT_PASSWORD: 
      ${MYSQL_ROOT_PASSWORD}
